routes/admin.php
    Route::post('admin/plan/bulk_delete', 'PlanController@bulk_delete');
    Route::post('admin/plan/change_subscription', 'PlanController@change_subscription');

    
    //Google Ads

    Route::get('admin/googleads/', 'GoogleAdsController@index')->name('google.ads');
    Route::get('admin/googleads/create', 'GoogleAdsController@create')->name('google.ads.create');
    Route::post('admin/googleads/create', 'GoogleAdsController@store')->name('google.ads.store');
    Route::get('admin/googleads/edit/{id}', 'GoogleAdsController@edit')->name('google.ads.edit');
    Route::put('admin/googleads/update/{id}', 'GoogleAdsController@update')->name('google.ads.update');
    Route::delete('admin/googleads/delete/{id}', 'GoogleAdsController@destroy')->name('google.ads.delete');
    Route::post('admin/googleads/bulk_delete', 'GoogleAdsController@bulk_delete');

    //ajax director
    Route::get('admin/directors/using/ajax', 'DirectorController@ajaxstore')->name('ajax.director');
    Route::get('admin/listofd', 'DirectorController@listofd')->name('listofd');

    //ajax actor

    Route::get('admin/actors/using/ajax', 'ActorController@ajaxstore')->name('ajax.actor');
    Route::get('admin/listofactor', 'ActorController@listofactor')->name('listofactor');

    // coupon controllers
    Route::resource('admin/coupons', 'CouponController');
    Route::post('admin/coupons/bulk_delete', 'CouponController@bulk_delete');
    Route::resource('admin/home_slider', 'HomeSliderController');
    Route::post('admin/home_slider/bulk_delete', 'HomeSliderController@bulk_delete');
    Route::post('admin/home_slider/reposition', 'HomeSliderController@slide_reposition')->name('slide_reposition');

    Route::get('admin/report', 'ReportController@get_report');

    /**************** revenue report ************************/
    Route::get('admin/report_revenue', 'ReportController@get_revenue_report')->name('revenue.report');
    Route::get('admin/report/data', 'ReportController@ajaxonLoad')->name('ajaxdatefilter');

    /*page setting routes*/
    Route::get('/admin/page-settings/', 'CustomStyleController@getPage')->name('pageset');

    Route::put('/admin/page-settings/{id}', 'CustomStyleController@updatePage')->name('pageset.update');

    /*Social Login setting routes*/
    Route::get('/admin/social-login/', 'SocialLoginController@index')->name('sociallogin');
    Route::put('/admin/social-login/{id}', 'SocialLoginController@updatePage')->name('sociallogin.update');
    Route::get('admin/social-login/', 'SocialLoginController@facebook')->name('set.facebook');
    Route::post('admin/facebook', 'SocialLoginController@updateFacebookKey')->name('key.facebook');
    Route::post('admin/google', 'SocialLoginController@updateGoogleKey')->name('key.google');
    Route::post('admin/gitlab', 'SocialLoginController@updategitlabKey')->name('key.gitlab');
    Route::post('admin/amazon', 'SocialLoginController@updateamazonKey')->name('key.amazon');

    /*end*/
    // adsense routes
    Route::get('/admin/adsensesetting/', 'AdsenseController@index')->name('adsense');
    Route::put('/admin/adsensesetting/{id}', 'AdsenseController@update')->name('adsense.update');

    /////////////////////////
    // Customizable Routes //
    /////////////////////////
    Route::resource('admin/customize/landing-page', 'LandingPageController');
    Route::post('admin/customize/landing-page/bulk_delete', 'LandingPageController@bulk_delete');
    Route::post('admin/customize/landing-page/reposition', 'LandingPageController@reposition')->name('landing_page_reposition');
    Route::get('admin/customize/auth-page-customize', 'AuthCustomizeController@index');
    Route::post('admin/customize/auth-page-customize', 'AuthCustomizeController@store');

    /////////////////////////
    // Customizable pages Routes //
    /////////////////////////
    Route::resource('admin/custom_page', 'CustomPageController');

    Route::resource('admin/home-block', 'HomeBlockController');

    Route::post('admin/home-block/bulk_delete', 'HomeBlockController@bulk_delete');


    Route::post('admin/custom_page/destroy/{id}', 'CustomPageController@destroy')->name('custom-page.destroy');
    Route::post('admin/custom_page/bulk_delete', 'CustomPageController@bulk_delete');

    //PWA Settings

    Route::get('/pwa-settings', 'PWAController@index')->name('pwa.setting.index');

    Route::post('/pwa/update/setting', 'PWAController@updatesetting')->name('pwa.setting.update');

    Route::post('/pwa/update/icons/setting', 'PWAController@updateicons')->name('pwa.icons.update');

    //manual payment

    Route::resource('admin/manual-payment', 'ManualPaymentController');

    //chat settings
    Route::get('admin/chat_settings', 'ChatSettingController@index')->name('chat.index');

    Route::post('admin/chat_settings', 'ChatSettingController@update');

    // Site Policies Get Method
    Route::get('admin/term&con', function () {
        $config = \App\Config::whereId(1)->first();
        return view('admin.term&con', compact('config'));
    })->name('term_con');
    Route::get('admin/pri_pol', function () {
        $config = \App\Config::whereId(1)->first();
        return view('admin.pri_pol', compact('config'));
    })->name('pri_pol');
    Route::get('admin/refund_pol', function () {
        $config = \App\Config::whereId(1)->first();
        return view('admin.refund_pol', compact('config'));
    })->name('refund_pol');
    Route::get('admin/copyright', function () {
        $config = \App\Config::whereId(1)->first();
        return view('admin.copyright', compact('config'));
    })->name('copyright');

    // Site Policies Patch Method
    Route::patch('admin/term&con', function (\Illuminate\Http\Request $request) {
        $config = \App\Config::whereId(1)->first();
        $input = $request->all();
        $input['terms_condition'] = clean($request->terms_condition);
        $config->update($input);
        return back()->with('updated', 'Terms & Condition has been updated');
    })->name('term&con');
    Route::patch('admin/pri_pol', function (\Illuminate\Http\Request $request) {
        $config = \App\Config::whereId(1)->first();
        $input = $request->all();
        $input['privacy_pol'] = clean($request->privacy_pol);
        $config->update($input);
        return back()->with('updated', 'Privacy Policy has been updated');
    })->name('pri_pol');
    Route::patch('admin/refund_pol', function (\Illuminate\Http\Request $request) {
        $config = \App\Config::whereId(1)->first();
        $input = $request->all();
        $input['refund_pol'] = clean($request->refund_pol);
        $config->update($input);
        return back()->with('updated', 'Refund Policy has been updated');
    })->name('refund_pol');
    Route::patch('admin/copyright', function (\Illuminate\Http\Request $request) {
        $config = \App\Config::whereId(1)->first();
        $input = $request->all();
        $input['copyright'] = clean($request->copyright);
        $config->update($input);
        return back()->with('updated', 'Copyright text has been updated');
    })->name('copyright');

    /////////////////////////////////
    // Language Translation Routes //
    /////////////////////////////////
    

    Route::get('/admin/translation/{local}', 'LanguageController@staticword')->name('languages.staticword');

    Route::post('/admin/update/{lang}/frontTranslations/content','LanguageController@frontupdate')->name('static.update');

    Route::get('admin/adminstatic/{local}', 'LanguageController@adminstaticword')->name('adminstatic.lang');

    Route::post('/admin/update/{lang}/adminTranslations/content','LanguageController@adminupdate')->name('admin.static.update');

    Route::get('/admin/edit/{lang}/staticTranslations', 'LanguageController@editStaticTrans')->name('static.trans');

    Route::post('/admin/update/{lang}/staticTranslations/content', 'LanguageController@updateStaticTrans')->name('static.trans.update');

    Route::post('/admin/update/{lang}/adminstaticTranslations/content', 'LanguageController@updateAdminStaticTrans')->name('static.admin.trans.update');

    Route::get('admin/lang', 'LanguageController@showlang')->name('show.lang');

    Route::get('admin/custom-static-words', 'LanguageController@customstatic');

    Route::get('admin/header-translations', 'HeaderTranslationController@index')->name('header-translation-index');
    Route::post('admin/header-translations', 'HeaderTranslationController@update');

    // Footer Translation Routes
    Route::get('admin/footer-translations', 'FooterTranslationController@index')->name('footer-translation-index');
    Route::post('admin/footer-translations', 'FooterTranslationController@update');

    // Home Page Translation Routes
    Route::get('admin/home-translations', 'HomeTranslationController@index')->name('home-translation-index');
    Route::post('admin/home-translations', 'HomeTranslationController@update');

    // Popover Detail Translation Routes
    Route::get('admin/popover-detail-translations', 'PopoverTranslationController@index')->name('popover-detail-translation-index');
    Route::post('admin/popover-detail-translations', 'PopoverTranslationController@update');

    Route::get('/admin/device-history', 'DashboardController@device_history')->name('device_history');

    //package feature
    Route::resource('admin/package_feature', 'PackageFeatureController');
    Route::post('admin/package_feature/bulk_delete', 'PackageFeatureController@bulk_delete');

    //mobile app settings route

    Route::resource('admin/appsettings', 'AppConfigController');

    //app slider

    Route::resource('admin/appslider', 'AppSliderController');
    Route::post('admin/appslider/bulk_delete', 'AppSliderController@bulk_delete');

routes/web.php
<?php

use App\Faq;
use App\User;
use App\Http\Controllers\HideForMeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



/*Route::get('/location', function () {

	$ip = Request::ip();
    $data = \Location::get($ip);
   // dd($data);
    var_dump($data);
    die();
   
});*/

Route::get('/location', 'MovieController@get_client_ip');

Route::get('/hidedata',[HideForMeController::class,'show'])->name('hidden.videos');

Route::post('hideforme/', 'HideForMeController@store')->name('hide.for.me');

Route::any('/notify/payhere', 'PayhereController@notify');

Route::get('/verify', 'TestController@getToken');

Route::get('verifylicense', 'InstallerController@verifylicense')->name('verifylicense');
Route::get('/install/procceed/verifyapp', 'InstallerController@verify')->name('verifyApp');
Route::post('verifycode', 'InitializeController@verify');

Route::get('/install/procceed/EULA', 'InstallerController@eula')->name('eulaterm');

Route::post('/install/procceed/EULA', 'InstallerController@storeeula')->name('store.eula');

/** SERVER CHECK**/
Route::get('/install/procceed/serverCheck', 'InstallerController@serverCheck')->name('servercheck');
Route::post('/install/procceed/serverCheck', 'InstallerController@storeserver')->name('store.server');

/** VERIFY COE ENTER*/
Route::get('/install/procceed/basic-setup', 'InstallerController@getBasicSetup')->name('installApp');
Route::post('store/basic-setup', 'InstallerController@storeBasicSetup')->name('storeBasicSetup');

/**  DATABASE SETUP*/
Route::get('/install/procceed/database-setup', 'InstallerController@getDatabaseSetup')->name('db.setup');
Route::post('stored/step2', 'InstallerController@step2')->name('store.step2');
Route::post('stored/step3', 'InstallerController@storeStep3')->name('store.step3');

Route::get('/existing/installation/', 'UpdateController@exitterm')->name('existterm');
Route::post('/existing/update/', 'UpdateController@updateeula')->name('store.updateeula');

Route::middleware(['IsInstalled', 'isActive', 'switch_languages', 'ip_block', 'comming_soon'])->group(function () {

    Route::get('manualpayment/{id}', 'ManualPaymentController@changemanualpayment')->name('quick.manualpayment.status');

    Route::post('/bttoken', 'BrainTreeController@accesstoken')->name('bttoken');

    Route::post('request-movie', 'RequestMovieController@store');
    Route::get('genre-sort', 'GenreController@sort');

    // download video code
    Route::get('/logout', 'LogoutController@logout')->name('custom.logout');

    Route::view('/offline', 'offline');
    Route::get('download/save/{file}', 'PrimeDetailController@filedownload')->name('file.download');

    Route::get('movie/save/{upload_video}', 'PrimeDetailController@moviedownload')->name('movie.download');
    Route::get('show/save/{upload_video}', 'PrimeDetailController@seasondownload')->name('season.download');
    Route::get('/user/movie/time/{endtime}/{movie_id}/{user_id}/{totaltime}', 'TimeHistoryController@movie_time');
    Route::get('/user/tv/time/{endtime}/{tv_id}/{totaltime}', 'TimeHistoryController@tv_time');
    Route::get('/user/watchhistory/{movie_id}/{type}', 'TimeHistoryController@watchhistory');

    Route::get('/user/episode/time/{endtime}/{episode_id}/{user_id}/{tv_id}/{totaltime}', 'TimeHistoryController@episode_time');

    // like and comment routes

    Route::get('comment/index', 'CommentController@index');
    Route::get('movie/comment/index', 'MovieCommentController@index');

    Route::post('movie/comment/store/{id}', 'MovieCommentController@store')->name('movie.comment.store');

    Route::post('movie/comment/reply/{cid}', 'MovieCommentController@reply')->name('movie.comment.reply');

    Route::delete('movie/comment/delete/{id}', 'MovieCommentController@deletecomment')->name('movie.comment.delete');

    Route::delete('movie/comment/reply/delete/{cid}', 'MovieCommentController@deletesubcomment')->name('movie.comment.subdelete');

    Route::get('comment/index', 'CommentController@index');

    Route::get('tvseries/comment/index', 'TVCommentController@index');

    Route::post('tvseries/comment/store/{id}', 'TVCommentController@store')->name('tv.comment.store');

    Route::post('tvseries/comment/reply/{cid}', 'TVCommentController@reply')->name('tv.comment.reply');

    Route::delete('tvseries/comment/delete/{id}', 'TVCommentController@deletecomment')->name('tv.comment.delete');

    Route::delete('tvseries/comment/reply/delete/{cid}', 'TVCommentController@deletesubcomment')->name('tv.comment.subdelete');

    Route::get('unlike/unlike', 'LikeController@unlike')->name('unlike');

    Route::get('like/add', 'LikeController@add')->name('addtolike');

    Route::post('comment/store/{id}', 'CommentController@store')->name('comment.store');

    Route::post('comment/reply/{cid}/{bid}', 'CommentController@reply')->name('comment.reply');

    Route::delete('blog/comment/delete/{id}', 'CommentController@deletecomment')->name('blog.comment.delete');

    Route::delete('blog/comment/reply/delete/{bid}', 'CommentController@deletesubcomment')->name('blog.comment.subdelete');

    Route::get('/movietrailer/{user}/{code}/{id}', 'WatchApiController@watch_trailer');
    Route::get('/watchmovie/{user}/{code}/{id}', 'WatchApiController@watch_movie');
    Route::get('/watchepisode/{user}/{code}/{id}', 'WatchApiController@watch_episode');
    Route::get('/watch/movie/iframe/{user}/{code}/{id}', 'WatchApiController@watch_iframe')->name('watchiframe');
    //api payment thankyou
    Route::get('/payment-successfully', 'WatchApiController@paymentSuccess');

    Route::get('verifyEmailFirst', 'Auth\RegisterController@verifyEmailFirst')->name('verifyEmailFirst');

    Route::get('verify/{email}/{verifyToken}', 'Auth\RegisterController@sendEmailDone')->name('sendEmailDone');

    // Test Controller Route to play video

    Route::get('/player', 'TestController@getVideo');

    // Paytem Routes
    Route::resource('/paytem', 'PaytemController');
    Route::get('/paytm-payment-redirect', 'PaytemController@handlePaytmRequest');
    Route::post('/paytm-callback', 'PaytemController@paytmCallback');

    //freepackagesubscription
    Route::post('free/subscription/{planid}', 'ManualPaymentController@freePackageSubscription')->name('free.package.subscription');

    // Routes With Only Language Switch Middleware
    Route::group(['middleware' => ['switch_languages']], function () {
        //Catlog view menus for user without logging in
        Route::get('/guest/{menus}', 'HomeController@guestindex')->name('guests');
        Route::get('/guest/watch/{id}', 'WatchController@watch')->name('guestwatchtrailer');
        Route::get('movie/guest/detail/{slug}', 'PrimeDetailController@showMovie');
        Route::get('/guest', 'HomeController@mainPage');
        Route::get('/guest/viewall/{menuid}/{menuname}', 'HomeController@showall')->name('guestshowall');
        Route::get('/guest/viewall/movies', 'HomeController@showallsinglemovies')->name('guestshowall2');
        Route::get('movies/guest/genre/{id}', 'HomeController@movie_genre');
        

        Route::get('show/all/guest/genres/{id}', 'HomeController@gusetshowallgenre')->name('show.in.guest.genre');
        Route::get('show/all/guest/langs/{id}', 'HomeController@guestshowallalang')->name('show.in.guest.alang');

        Route::get('home/search', 'HomeController@search')->name('search');
        Route::get('quick/search', 'HomeController@quicksearch')->name('quick.search');

        Route::get('video/detail/director_search/{director}', 'HomeController@director_search');
        Route::get('video/detail/actor_search/{actor}', 'HomeController@actor_search');
        Route::get('video/detail/genre_search/{genre}', 'HomeController@genre_search');

        Route::get('/page/{slug}', 'CustomPageController@show')->name('custom.page.show');

        if (Auth::user()) {
            // menu routes
            Route::get('/{menu}', 'HomeController@index')->name('home');
        } else {
            // main page route
            Route::get('/', 'HomeController@mainPage');

        }

        // Faq routes

        Route::get('faq', function () {
            $faqs = Faq::all();
            return view('faq', compact('faqs'));
        });

        // general pages routes
        Route::view('terms_condition', 'term_condition');
        Route::view('privacy_policy', 'privacy_pol');
        Route::view('refund_policy', 'refund_pol');
        Route::view('seo', 'seo');

        // Auth Routes
        Auth::routes();

    });

    //Affiliate route

    Route::get('/user/affiliate/settings', 'AffilateController@userdashboard')->name('user.affiliate.settings');

    //2FA
    Route::post('/valid-2fa', 'TwoFactorController@login')->middleware('auth');

    // Language switch middleware
    Route::get('language-switch/{local}', 'LanguageSwitchController@languageSwitch')->name('languageSwitch');

    // Routes With Web, Auth Middlewares
    Route::get('contactus', 'ContactController@contact')->name('contactus');
    Route::post('send/contactus', 'ContactController@send')->name('send.contactus');   
     
    Route::group(['middleware' => ['web', 'auth', 'switch_languages']], function () {
        // User Account routes without subscription
        Route::get('account', 'UserAccountController@index');

        Route::post('/payviarazorpaysuccess/{planid}', 'PayViaRazorpayController@success')->name('paysuccess');

        
        Route::get('account/profile', 'UserAccountController@edit_profile');
        Route::post('account/profile', 'UserAccountController@update_profile')->name('user.profile');
        Route::post('account/profile/age', 'UsersController@update_age')->name('user.age');
        Route::post('account/profile/address', 'UsersController@update_address')->name('user.address');
        Route::post('account/profile/uploadimage', 'UsersController@update_image')->name('user.uploadImage');

resources/views/admin/landing-page/index.blade.php
@extends('layouts.master')
@section('title',__('Landing Pages'))
@section('breadcum')
	<div class="breadcrumbbar">
                <h4 class="page-title">{{ __('Landing Pages') }}</h4>
                <div class="breadcrumb-list">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item"><a href="{{url('/admin')}}">{{ __('Dashboard') }}</a></li>
                      <li class="breadcrumb-item active" aria-current="page">{{ __('Landing Pages') }}</li>
                    </ol>
                </div> 
    </div>
@endsection
@section('maincontent')
<div class="contentbar">
<div class="row">
  
  <div class="col-lg-12">
      <div class="card m-b-50">
          <div class="card-header">
            <button type="button" class="float-right btn btn-danger-rgba mr-2 " data-toggle="modal"
          data-target="#bulk_delete"><i class="feather icon-trash mr-2"></i> {{ __('Delete Selected') }} </button>
            <a href="{{route('landing-page.create')}}" class="float-right btn btn-primary-rgba mr-2"><i
                class="feather icon-plus mr-2"></i>{{ __('Create A Block') }}</a>
                <div id="bulk_delete" class="delete-modal modal fade" role="dialog">
                  <div class="modal-dialog modal-sm">
                      <!-- Modal content-->
                      <div class="modal-content">
                          <div class="modal-header">
                              <button type="button" class="close"
                                  data-dismiss="modal">&times;</button>
                              <div class="delete-icon"></div>
                          </div>
                          <div class="modal-body text-center">
                              <h4 class="modal-heading">{{__('Are You Sure ?')}}</h4>
                              <p>{{__('Do you really want to delete selected item names here? This
                                  process
                                  cannot be undone.')}}</p>
                          </div>
                          <div class="modal-footer">
                            {!! Form::open(['method' => 'POST', 'action' => 'LandingPageController@bulk_delete', 'id' => 'bulk_delete_form']) !!}
                                  <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">{{__('No')}}</button>
                                  <button type="submit" class="btn btn-danger">{{__('Yes')}}</button>
                              {!! Form::close() !!}
                          </div>
                      </div>
                  </div>
              </div>
                <h5 class="card-title"> {{__("Landing Pages")}}</h5>
          </div>
          
          <div class="card-body">
           
              <div class="table-responsive">
                <table id="full_detail_table" class="table table-borderd responsive " style="width: 100%">

                    <thead>
                      <th>
                        <div class="inline">
                          <input id="checkboxAll" type="checkbox" class="filled-in" name="checked[]" value="all" id="checkboxAll">
                          <label for="checkboxAll" class="material-checkbox"></label>
                        </div>
                      </th>
                      <th>{{__('Image')}}</th>
                      <th>{{__('Heading')}}</th>
                      <th>{{__('Details')}}</th>
                      <th>{{__('Button')}}</th>
                      <th>{{__('Image Position')}}</th>
                      <th>{{__('Actions')}}</th>
                    </thead>
                
                    <tbody>

                      @if ($landing_pages)
                      <tbody>
                        @foreach ($landing_pages as $key => $block)
                          <tr id="item-{{$block->id}}">
                            <td>
                              <div class="inline">
                                <input type="checkbox" form="bulk_delete_form" class="filled-in material-checkbox-input" name="checked[]" value="{{$block->id}}" id="checkbox{{$block->id}}">
                                <label for="checkbox{{$block->id}}" class="material-checkbox"></label>
                              </div>
                              {{$key+1}}
                            </td>
                            <td>
                              @if ($block->image != null) 
                                <img src="{{ asset('images/main-home/'.$block->image) }}" width="140px" height="50px" class="img-responsive">
                              @endif
                            </td>
                            <td>{{$block->heading}}</td>
                            <td title="{{$block->detail}}">{{str_limit($block->detail, 50)}}</td>
                            <td>
                              @if ($block->button == 1)
                                @if ($block->button_link == 'login')
                                  <a href="#" data-toggle="tooltip" data-original-title="Login Link" class="btn btn-prime">{{$block->button_text}}</a>
                                @elseif ($block->button_link == 'register')  
                                  <a href="#" data-toggle="tooltip" data-original-title="Register Link" class="btn btn-prime">{{$block->button_text}}</a>
                                @endif
                              @endif
                            </td>
                            <td>{{$block->left == 1 ? 'Left' : 'Right'}}</td>
                            <td>
                              <div class="admin-table-action-block">
                                <a href="{{route('landing-page.edit', $block->id)}}" data-toggle="tooltip" data-original-title="{{__('Edit')}}" class="btn btn-round btn-outline-primary"> <i class="fa fa-edit"></i></a>
                                <button type="button" class="btn btn-round btn-outline-danger" data-toggle="modal" data-target="#delete{{$block->id}}"><i class="fa fa-trash"></i> </button>
                              </div>
                            </td>
                          </tr>
                          <div id="delete{{$block->id}}" class="delete-modal modal fade" role="dialog">
                            <div class="modal-dialog modal-sm">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close"
                                            data-dismiss="modal">&times;</button>
                                        <div class="delete-icon"></div>
                                    </div>
                                    <div class="modal-body text-center">
                                        <h4 class="modal-heading">{{__('Are You Sure ?')}}</h4>
                                        <p>{{__('Do you really want to delete selected item names here? This
                                            process
                                            cannot be undone.')}}</p>
                                    </div>
                                    <div class="modal-footer">
                                      {!! Form::open(['method' => 'DELETE', 'action' => ['LandingPageController@destroy', $block->id]]) !!}
                                            <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">{{__('No')}}</button>
                                            <button type="submit" class="btn btn-danger">{{__('Yes')}}</button>
                                        {!! Form::close() !!}
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                      </tbody>
                    @endif
                </table>
            </div>
        </div>
    </div>
</div>
</div>
@endsection 
@section('script')
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script> -->
<script>
  (function($){
    $('#checkboxAll').on('change', function(){
      if($(this).prop("checked") == true){
        $('.material-checkbox-input').attr('checked', true);
      }
      else if($(this).prop("checked") == false){
        $('.material-checkbox-input').attr('checked', false);
      }
    });

    $('table.db tbody').sortable({
      cursor: "move",
      revert: true,
      placeholder: 'sort-highlight',
      connectWith: '.connectedSortable',
      forcePlaceholderSize: true,
      zIndex: 999999,
      axis: 'y',
      update: function(event, ui) {
        var data = $(this).sortable('serialize');
        app.$http.post('{{route('landing_page_reposition')}}', {item: data}).then((response) => {
          console.log(data);
          console.log('re');
          console.log(response);
        }).catch((e) => {
          console.log($(this).sortable('serialize'));
          console.log(e);
          console.log('err');
        });
      }
    });
  })(jQuery);
  // var app = new Vue({});
  
  $(window).resize(function() {
    $('table.db tr').css('min-width', $('table.db').width());
  });
</script>
@endsection