routes/admin.php
        return back()->with('updated', 'Copyright text has been updated');
    })->name('copyright');

    /////////////////////////////////
    // Language Translation Routes //
    /////////////////////////////////
    

    Route::get('/admin/translation/{local}', 'LanguageController@staticword')->name('languages.staticword');

    Route::post('/admin/update/{lang}/frontTranslations/content','LanguageController@frontupdate')->name('static.update');

    Route::get('admin/adminstatic/{local}', 'LanguageController@adminstaticword')->name('adminstatic.lang');

    Route::post('/admin/update/{lang}/adminTranslations/content','LanguageController@adminupdate')->name('admin.static.update');

    Route::get('/admin/edit/{lang}/staticTranslations', 'LanguageController@editStaticTrans')->name('static.trans');

    Route::post('/admin/update/{lang}/staticTranslations/content', 'LanguageController@updateStaticTrans')->name('static.trans.update');

    Route::post('/admin/update/{lang}/adminstaticTranslations/content', 'LanguageController@updateAdminStaticTrans')->name('static.admin.trans.update');

    Route::get('admin/lang', 'LanguageController@showlang')->name('show.lang');

    Route::get('admin/custom-static-words', 'LanguageController@customstatic');

    Route::get('admin/header-translations', 'HeaderTranslationController@index')->name('header-translation-index');
    Route::post('admin/header-translations', 'HeaderTranslationController@update');

    // Footer Translation Routes
    Route::get('admin/footer-translations', 'FooterTranslationController@index')->name('footer-translation-index');
    Route::post('admin/footer-translations', 'FooterTranslationController@update');

    // Home Page Translation Routes
    Route::get('admin/home-translations', 'HomeTranslationController@index')->name('home-translation-index');
    Route::post('admin/home-translations', 'HomeTranslationController@update');

    // Popover Detail Translation Routes
    Route::get('admin/popover-detail-translations', 'PopoverTranslationController@index')->name('popover-detail-translation-index');
    Route::post('admin/popover-detail-translations', 'PopoverTranslationController@update');

    Route::get('/admin/device-history', 'DashboardController@device_history')->name('device_history');

    //package feature
    Route::resource('admin/package_feature', 'PackageFeatureController');
    Route::post('admin/package_feature/bulk_delete', 'PackageFeatureController@bulk_delete');

    //mobile app settings route

    Route::resource('admin/appsettings', 'AppConfigController');

    //app slider

    Route::resource('admin/appslider', 'AppSliderController');
    Route::post('admin/appslider/bulk_delete', 'AppSliderController@bulk_delete');
    Route::post('admin/appslider/reposition', 'AppSliderController@slide_reposition')->name('app_slide_reposition');

    //App ui Shorting
    Route::resource('admin/appUiShorting', 'AppUiShortigController');
    Route::post('admin/appUi/reposition', 'AppUiShortigController@reposition')->name('app_ui_reposition');

    // Database Backup

    Route::get('admin/backups/', 'BackupController@get')->name('admin.backup.settings');
    Route::post('admin/backup/path', 'BackupController@updatepath')->name('admin.backup.path');
    Route::get('admin/download/{filename}', 'BackupController@download')->name('admin.backup.download');
    Route::get('admin/backups/process', 'BackupController@process')->name('admin.backup.process');

    //clear cache
    Route::get('admin/clear-cache', 'BackupController@clearcahe')->name('clear.cache');

    // System Status
    Route::get('admin/system-status', 'BackupController@system_status')->name('system.status');

    // remove public
    Route::get('admin/remove/public', 'BackupController@getremove_public')->name('get.remove.public');
    Route::post('admin/remove-public', 'BackupController@remove_public')->name('remove.public');

    //onesignal notification route
    Route::get('/admin/push-notifications', 'PushNotificationsController@index')->name('admin.push.noti.settings');
    Route::post('/admin/one-signal/keys', 'PushNotificationsController@updateKeys')->name('admin.onesignal.keys');
    Route::post('/admin/push-notifications', 'PushNotificationsController@push')->name('admin.push.notif');

    //menual payment method
    Route::get('admin/manual-payment-settings', 'ManualPaymentGatewayController@getindex')->name('manual.payment.gateway');
    Route::post('admin/manual-payment-settings', 'ManualPaymentGatewayController@store')->name('manual.payment.gateway.store');
    Route::post('admin/manual-payment-settings/{id}', 'ManualPaymentGatewayController@update')->name('manual.payment.gateway.update');
    Route::delete('admin/manual-payment-settings/{id}', 'ManualPaymentGatewayController@delete')->name('manual.payment.gateway.delete');

    //Addon Manager Route
    Route::get('/admin/addon-manger', 'AddOnManagerController@index')->name('addonmanger.index');
    Route::post('/admin/toggle/module', 'AddOnManagerController@toggle');
    Route::post('/admin/addon/install', 'AddOnManagerController@install')->name('addon.install');
    Route::post('/admin/addon/delete', 'AddOnManagerController@delete')->name('addon.delete');

    //Label Routes
    Route::resource('/admin/label', 'LabelController');
    Route::post('admin/label/bulk_delete', 'LabelController@bulk_delete');

    //Category Routes
    Route::resource('/admin/category', 'CategoryController');
    Route::post('admin/category/bulk_delete', 'CategoryController@bulk_delete');

    //Sub Category Routes
    Route::resource('/admin/sub_category', 'SubCategoryController');
    Route::post('admin/sub_category/subs/bulk_delete', 'SubCategoryController@bulk_delete');

    //Comment in admin

    Route::get('/admin/comments', 'AdminCommentController@index')->name('admin.comment.index');
    Route::delete('/admin/comments/{id}', 'AdminCommentController@destroy')->name('comments.destroy');
    Route::get('/quick/change/comment_status/{id}', 'QuickUpdateController@commentchange')->name('quick.comment.status');
    Route::post('admin/comments/bulk_delete', 'AdminCommentController@bulk_delete');

    //SubComment settings in Admin

    Route::get('/admin/subcomments', 'AdminCommentController@subcommentindex')->name('admin.subcomment.index');
    Route::delete('/admin/subcomments/{id}', 'AdminCommentController@subcommentdestroy')->name('subcomments.destroy');
    Route::get('/quick/change/subcomment_status/{id}', 'QuickUpdateController@subcommentchange')->name('quick.subcomment.status');
    Route::post('admin/subcomments/bulk_delete', 'AdminCommentController@sub_bulk_delete');

    //color scheme
    Route::get('admin/color-scheme', 'ColorSchemeController@index')->name('admin.color.scheme');
    Route::post('admin/color-scheme/store', 'ColorSchemeController@store');

    //Quickfix update
    Route::post('/admin/merge-quick-update', 'UpdateController@mergeQuickupdate');

    //currency routes
    Route::resource('/admin/currency', 'CurrencyController');

    Route::post('/admin/save/exchange/key', 'CurrencyController@saveSetting')->name('currency.exchanges.save');

    Route::post("/admin/auto_update_currency", "CurrencyController@auto_update_currency")->name('auto.update.rates');

    Route::get("/admin/checkout-currency/{id}", "CurrencyController@checkoutCurrency");
    
    Route::post("/admin/destroy-currency/{id}", "CurrencyController@destroy")->name('currency.destroy');

    Route::post("/admin/checkout-currency/payment/update", "CurrencyController@checkoutPayment")->name('checkout.payment.method');

    //roles and permission
    Route::resource('/admin/roles', 'Roles\RolesController');
    Route::view('permission', 'per');
    Route::view('permission/bulk', 'perbulk');
    Route::post('permission/bulk', 'Roles\RolesController@bulkPermission');
    Route::post('permission', 'Roles\RolesController@createPermission');
    Route::post('admin/roles/{id}/delete', 'Roles\RolesController@destroy');

    //import demo
    Route::get('/admin/import-demo', 'OtherController@getImportDemo')->name('admin.import.demo');
    Route::post('/admin/import/import-demo', 'OtherController@ImportDemo');
    Route::post('/admin/reset-demo', 'OtherController@DemoReset');

    //get secret key for api
    Route::get('getsecretkey', 'AppConfigController@getkey')->name('get.api.key');
    Route::post('createkey', 'AppConfigController@createKey')->name('apikey.create');

    //affliate routes

    Route::name('admin.affilate.')->prefix('/admin/affiliate')->group(function () {

        Route::get('/settings', 'AffilateController@settings')->name('settings');
        Route::post('/settings', 'AffilateController@update')->name('update');
        Route::get('/reports', 'AffilateController@reports')->name('dashboard');

    });

    // wallet routes

    Route::prefix('/admin/wallet')->group(function () {

        Route::get('/settings', 'WalletSettingController@index')->name('admin.wallet.settings');
        Route::post('/settings/update', 'WalletSettingController@update')->name('admin.update.wallet.settings');
    });

    //bulk import
    Route::post('/admin/import/actors', [ActorController::class, 'importactors']);
    Route::post('/admin/import/directors', [DirectorController::class, 'importdirectors']);
    Route::post('/admin/import/genres', [GenreController::class, 'importgenres']);
    Route::post('/admin/import/movies', [MovieController::class, 'importmovies']);
    Route::post('/admin/import/live-tv', [LiveTvController::class, 'importlivetv']);

    //site map
    Route::get('/sitemap', 'SiteMapController@sitemapGenerator');

    Route::get('/sitemap/download', 'SiteMapController@download');


routes/web.php
<?php

use App\Faq;
use App\User;
use App\Http\Controllers\HideForMeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



/*Route::get('/location', function () {

	$ip = Request::ip();
    $data = \Location::get($ip);
   // dd($data);
    var_dump($data);
    die();
   
});*/

Route::get('/location', 'MovieController@get_client_ip');

Route::get('/hidedata',[HideForMeController::class,'show'])->name('hidden.videos');

Route::post('hideforme/', 'HideForMeController@store')->name('hide.for.me');

Route::any('/notify/payhere', 'PayhereController@notify');

Route::get('/verify', 'TestController@getToken');

Route::get('verifylicense', 'InstallerController@verifylicense')->name('verifylicense');
Route::get('/install/procceed/verifyapp', 'InstallerController@verify')->name('verifyApp');
Route::post('verifycode', 'InitializeController@verify');

Route::get('/install/procceed/EULA', 'InstallerController@eula')->name('eulaterm');

Route::post('/install/procceed/EULA', 'InstallerController@storeeula')->name('store.eula');

/** SERVER CHECK**/
Route::get('/install/procceed/serverCheck', 'InstallerController@serverCheck')->name('servercheck');
Route::post('/install/procceed/serverCheck', 'InstallerController@storeserver')->name('store.server');

/** VERIFY COE ENTER*/
Route::get('/install/procceed/basic-setup', 'InstallerController@getBasicSetup')->name('installApp');
Route::post('store/basic-setup', 'InstallerController@storeBasicSetup')->name('storeBasicSetup');

/**  DATABASE SETUP*/
Route::get('/install/procceed/database-setup', 'InstallerController@getDatabaseSetup')->name('db.setup');
Route::post('stored/step2', 'InstallerController@step2')->name('store.step2');
Route::post('stored/step3', 'InstallerController@storeStep3')->name('store.step3');

Route::get('/existing/installation/', 'UpdateController@exitterm')->name('existterm');
Route::post('/existing/update/', 'UpdateController@updateeula')->name('store.updateeula');

Route::middleware(['IsInstalled', 'isActive', 'switch_languages', 'ip_block', 'comming_soon'])->group(function () {

    Route::get('manualpayment/{id}', 'ManualPaymentController@changemanualpayment')->name('quick.manualpayment.status');

    Route::post('/bttoken', 'BrainTreeController@accesstoken')->name('bttoken');

    Route::post('request-movie', 'RequestMovieController@store');
    Route::get('genre-sort', 'GenreController@sort');

    // download video code
    Route::get('/logout', 'LogoutController@logout')->name('custom.logout');

    Route::view('/offline', 'offline');
    Route::get('download/save/{file}', 'PrimeDetailController@filedownload')->name('file.download');

    Route::get('movie/save/{upload_video}', 'PrimeDetailController@moviedownload')->name('movie.download');
    Route::get('show/save/{upload_video}', 'PrimeDetailController@seasondownload')->name('season.download');
    Route::get('/user/movie/time/{endtime}/{movie_id}/{user_id}/{totaltime}', 'TimeHistoryController@movie_time');
    Route::get('/user/tv/time/{endtime}/{tv_id}/{totaltime}', 'TimeHistoryController@tv_time');
    Route::get('/user/watchhistory/{movie_id}/{type}', 'TimeHistoryController@watchhistory');

    Route::get('/user/episode/time/{endtime}/{episode_id}/{user_id}/{tv_id}/{totaltime}', 'TimeHistoryController@episode_time');

    // like and comment routes

    Route::get('comment/index', 'CommentController@index');
    Route::get('movie/comment/index', 'MovieCommentController@index');

    Route::post('movie/comment/store/{id}', 'MovieCommentController@store')->name('movie.comment.store');

    Route::post('movie/comment/reply/{cid}', 'MovieCommentController@reply')->name('movie.comment.reply');

    Route::delete('movie/comment/delete/{id}', 'MovieCommentController@deletecomment')->name('movie.comment.delete');

    Route::delete('movie/comment/reply/delete/{cid}', 'MovieCommentController@deletesubcomment')->name('movie.comment.subdelete');

    Route::get('comment/index', 'CommentController@index');

    Route::get('tvseries/comment/index', 'TVCommentController@index');

    Route::post('tvseries/comment/store/{id}', 'TVCommentController@store')->name('tv.comment.store');

    Route::post('tvseries/comment/reply/{cid}', 'TVCommentController@reply')->name('tv.comment.reply');

    Route::delete('tvseries/comment/delete/{id}', 'TVCommentController@deletecomment')->name('tv.comment.delete');

    Route::delete('tvseries/comment/reply/delete/{cid}', 'TVCommentController@deletesubcomment')->name('tv.comment.subdelete');

    Route::get('unlike/unlike', 'LikeController@unlike')->name('unlike');

    Route::get('like/add', 'LikeController@add')->name('addtolike');

    Route::post('comment/store/{id}', 'CommentController@store')->name('comment.store');

    Route::post('comment/reply/{cid}/{bid}', 'CommentController@reply')->name('comment.reply');

    Route::delete('blog/comment/delete/{id}', 'CommentController@deletecomment')->name('blog.comment.delete');

    Route::delete('blog/comment/reply/delete/{bid}', 'CommentController@deletesubcomment')->name('blog.comment.subdelete');

    Route::get('/movietrailer/{user}/{code}/{id}', 'WatchApiController@watch_trailer');
    Route::get('/watchmovie/{user}/{code}/{id}', 'WatchApiController@watch_movie');
    Route::get('/watchepisode/{user}/{code}/{id}', 'WatchApiController@watch_episode');
    Route::get('/watch/movie/iframe/{user}/{code}/{id}', 'WatchApiController@watch_iframe')->name('watchiframe');
    //api payment thankyou
    Route::get('/payment-successfully', 'WatchApiController@paymentSuccess');

    Route::get('verifyEmailFirst', 'Auth\RegisterController@verifyEmailFirst')->name('verifyEmailFirst');

    Route::get('verify/{email}/{verifyToken}', 'Auth\RegisterController@sendEmailDone')->name('sendEmailDone');

    // Test Controller Route to play video

    Route::get('/player', 'TestController@getVideo');

    // Paytem Routes
    Route::resource('/paytem', 'PaytemController');
    Route::get('/paytm-payment-redirect', 'PaytemController@handlePaytmRequest');
    Route::post('/paytm-callback', 'PaytemController@paytmCallback');

    //freepackagesubscription
    Route::post('free/subscription/{planid}', 'ManualPaymentController@freePackageSubscription')->name('free.package.subscription');

    // Routes With Only Language Switch Middleware
    Route::group(['middleware' => ['switch_languages']], function () {
        //Catlog view menus for user without logging in
        Route::get('/guest/{menus}', 'HomeController@guestindex')->name('guests');
        Route::get('/guest/watch/{id}', 'WatchController@watch')->name('guestwatchtrailer');
        Route::get('movie/guest/detail/{slug}', 'PrimeDetailController@showMovie');
        Route::get('/guest', 'HomeController@mainPage');
        Route::get('/guest/viewall/{menuid}/{menuname}', 'HomeController@showall')->name('guestshowall');
        Route::get('/guest/viewall/movies', 'HomeController@showallsinglemovies')->name('guestshowall2');
        Route::get('movies/guest/genre/{id}', 'HomeController@movie_genre');
        

        Route::get('show/all/guest/genres/{id}', 'HomeController@gusetshowallgenre')->name('show.in.guest.genre');
        Route::get('show/all/guest/langs/{id}', 'HomeController@guestshowallalang')->name('show.in.guest.alang');

        Route::get('home/search', 'HomeController@search')->name('search');
        Route::get('quick/search', 'HomeController@quicksearch')->name('quick.search');

        Route::get('video/detail/director_search/{director}', 'HomeController@director_search');
        Route::get('video/detail/actor_search/{actor}', 'HomeController@actor_search');
        Route::get('video/detail/genre_search/{genre}', 'HomeController@genre_search');

        Route::get('/page/{slug}', 'CustomPageController@show')->name('custom.page.show');

        if (Auth::user()) {
            // menu routes
            Route::get('/{menu}', 'HomeController@index')->name('home');
        } else {
            // main page route
            Route::get('/', 'HomeController@mainPage');

        }

        // Faq routes

        Route::get('faq', function () {
            $faqs = Faq::all();
            return view('faq', compact('faqs'));
        });

        // general pages routes
        Route::view('terms_condition', 'term_condition');
        Route::view('privacy_policy', 'privacy_pol');
        Route::view('refund_policy', 'refund_pol');
        Route::view('seo', 'seo');

        // Auth Routes
        Auth::routes();

    });

    //Affiliate route

    Route::get('/user/affiliate/settings', 'AffilateController@userdashboard')->name('user.affiliate.settings');

    //2FA
    Route::post('/valid-2fa', 'TwoFactorController@login')->middleware('auth');

    // Language switch middleware
    Route::get('language-switch/{local}', 'LanguageSwitchController@languageSwitch')->name('languageSwitch');

    // Routes With Web, Auth Middlewares
    Route::get('contactus', 'ContactController@contact')->name('contactus');
    Route::post('send/contactus', 'ContactController@send')->name('send.contactus');   
     
    Route::group(['middleware' => ['web', 'auth', 'switch_languages']], function () {
        // User Account routes without subscription
        Route::get('account', 'UserAccountController@index');

        Route::post('/payviarazorpaysuccess/{planid}', 'PayViaRazorpayController@success')->name('paysuccess');

        
        Route::get('account/profile', 'UserAccountController@edit_profile');
        Route::post('account/profile', 'UserAccountController@update_profile')->name('user.profile');
        Route::post('account/profile/age', 'UsersController@update_age')->name('user.age');
        Route::post('account/profile/address', 'UsersController@update_address')->name('user.address');
        Route::post('account/profile/uploadimage', 'UsersController@update_image')->name('user.uploadImage');

resources/views/admin/label/action.blade.php
<div class="dropdown">
  <button class="btn btn-round btn-outline-primary" type="button"
      id="CustomdropdownMenuButton1" data-toggle="dropdown"
      aria-haspopup="true" aria-expanded="false"><i
          class="feather icon-more-vertical-"></i></button>
  <div class="dropdown-menu" aria-labelledby="CustomdropdownMenuButton1">
      @can('label.edit')
      <a class="dropdown-item" href="{{ route('label.edit',$id) }}"><i class="feather icon-edit mr-2"></i>{{ __("Edit") }}</a>
      @endcan
      @can('label.delete')
      <a class="dropdown-item btn btn-link" data-toggle="modal" data-target="#delete{{ $id }}">


          <i class="feather icon-delete mr-2"></i>{{ __("Delete") }}</a>
      </a>
      @endcan
  </div>
</div>

<!-- delete Modal start -->
<div class="modal fade bd-example-modal-sm" id="delete{{$id}}"
  tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="exampleSmallModalLabel">Delete</h5>
              <button type="button" class="close" data-dismiss="modal"
                  aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <div class="modal-body">
              <h4>{{ __('Are You Sure ?')}}</h4>
              <p>{{ __('Do you really want to delete')}}
                  {{ __('This process cannot be undone.')}}</p>
          </div>
          <div class="modal-footer">
            <form method="POST" action="{{route("label.destroy", $id)}}">
              @method("DELETE")
              @csrf  
                  <button type="reset" class="btn btn-secondary"
                      data-dismiss="modal">No</button>
                  <button type="submit" class="btn btn-primary">Yes</button>
              </form>
          </div>
      </div>
  </div>
</div>
<!-- delete Model ended -->

resources/views/admin/label/create.blade.php
@extends('layouts.master')
@section('title',__('Create Label'))
@section('breadcum')
	<div class="breadcrumbbar">
                <h4 class="page-title">{{ __('HOME') }}</h4>
                <div class="breadcrumb-list">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item"><a href="{{url('/admin')}}">{{ __('Dashboard') }}</a></li>
                      <li class="breadcrumb-item active" aria-current="page">{{ __('Create Label') }}</li>
                    </ol>
                </div>  
    </div>
@endsection
@section('maincontent')
<div class="contentbar">
  <div class="row">
    @if ($errors->any())  
  <div class="alert alert-danger" role="alert">
  @foreach($errors->all() as $error)     
  <p>{{ $error}}<button type="button" class="close" data-dismiss="alert" aria-label="Close">
  <span aria-hidden="true" style="color:red;">&times;</span></button></p>
      @endforeach  
  </div>
  @endif
    <div class="col-lg-6">
      <div class="card m-b-50">
        <div class="card-header">
          <a href="{{url('admin/label')}}" class="float-right btn btn-primary-rgba mr-2"><i
            class="feather icon-arrow-left mr-2"></i>{{ __('Back') }}</a>
          <h5 class="box-title">{{__('Create Label')}}</h5>
        </div>
        <div class="card-body ml-2">
          {!! Form::open(['method' => 'POST', 'action' => 'LabelController@store']) !!}
            <div class="row">
              <div class="col-md-12">
                <div class="form-group text-dark{{ $errors->has('name') ? ' has-error' : '' }}">
                  {!! Form::label('name', __('Name')) !!}
                  {!! Form::text('name', old('name'), ['class' => 'form-control', 'required' => 'required', 'placeholder' => __('Please Enter Label name')]) !!}
                  <small class="text-danger">{{ $errors->first('name') }}</small>
              </div>
            </div>
              
              
                <div class="form-group">
                  <button type="reset" class="btn btn-success-rgba">{{__('Reset')}}</button>
                  <button type="submit" class="btn btn-primary-rgba"><i class="fa fa-check-circle"></i>
                    {{ __('Update') }}</button>
                </div>
                {!! Form::close() !!}
                <div class="clear-both"></div>
            

      </div>
    </div>
  </div>
</div>
</div>
@endsection 
@section('script')
@endsection

resources/views/admin/label/index.blade.php
@extends('layouts.master')
@section('title',__('All Labels'))
@section('breadcum')
	<div class="breadcrumbbar">
                <h4 class="page-title">{{ __('Labels') }}</h4>
                <div class="breadcrumb-list">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item"><a href="{{url('/admin')}}">{{ __('Dashboard') }}</a></li>
                      <li class="breadcrumb-item active" aria-current="page">{{ __('Labels') }}</li>
                    </ol>
                </div> 
    </div>
@endsection
@section('maincontent')
<div class="contentbar"> 
    <div class="row">
        <div class="col-md-12">

            <div class="card m-b-50">
                <div class="card-header">
                    <button type="button" class="float-right btn btn-danger-rgba mr-2 " data-toggle="modal"
            data-target="#bulk_delete"><i class="feather icon-trash mr-2"></i> {{ __('Delete Selected') }} </button>
            <a href="{{route('label.create')}}" class="float-right btn btn-primary-rgba mr-2"><i
                class="feather icon-plus mr-2"></i>{{ __('Add Labels') }} </a>
                    <h5 class="card-title">{{ __('All Labels') }}</h5>
                    
                </div> 

                <div class="card-body">
                    <div class="table-responsive">
                         <table id="labelTable" class="table table-borderd">

                            <thead>
                              <th>
                                <div class="inline">
                                  <input id="checkboxAll" type="checkbox" class="filled-in" name="checked[]" value="all" id="checkboxAll">
                                  <label for="checkboxAll" class="material-checkbox"></label>
                                </div>
                              </th>
                              <th>{{__('Name')}}</th>
                              <th>{{__('Created At')}}</th>
                              <th>{{__('Updated At')}}</th>
                              <th>{{__('Actions')}}</th>
                            </thead>

                            @if (isset($labels))
                              <tbody>
                              
                              </tbody>
                            @endif

                            <div id="bulk_delete" class="delete-modal modal fade" role="dialog">
                                <div class="modal-dialog modal-sm">
                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close"
                                                data-dismiss="modal">&times;</button>
                                            <div class="delete-icon"></div>
                                        </div>
                                        <div class="modal-body text-center">
                                            <h4 class="modal-heading">{{__('Are You Sure ?')}}</h4>
                                            <p>{{__('Do you really want to delete selected item names here? This
                                                process
                                                cannot be undone.')}}</p>
                                        </div>
                                        <div class="modal-footer">
                                          {!! Form::open(['method' => 'POST', 'action' => 'LabelController@bulk_delete', 'id' => 'bulk_delete_form']) !!}
                                                <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">{{__('No')}}</button>
                                                <button type="submit" class="btn btn-danger">{{__('Yes')}}</button>
                                            {!! Form::close() !!}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        

                        </table>                  
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection 
@section('script')
   
<script>
  $(function(){
    $('#checkboxAll').on('change', function(){
      if($(this).prop("checked") == true){
        $('.material-checkbox-input').attr('checked', true);
      }
      else if($(this).prop("checked") == false){
        $('.material-checkbox-input').attr('checked', false);
      }
    });
  });
</script>
 <script>
  $(function () {
    "use strict";
    jQuery.noConflict();
    var table;
    if($.fn.dataTable.isDataTable('#labelTable')){
      table = $('#labelTable').DataTable();
    }else{
      table = $('#labelTable').DataTable({
        processing: true,
        serverSide: true,
        responsive: true,
        autoWidth: false,
        scrollCollapse: true,
        ajax: "{{ route('label.index') }}",
        columns: [
            {data: 'checkbox', name: 'checkbox',orderable: false, searchable: false},
            {data: 'name', name: 'name'},
            {data: 'created_at', name: 'created_at'},
            {data: 'updated_at', name: 'updated_at'},
            {data: 'action', name: 'action',searchable: false}
           
        ],
        dom : 'lBfrtip',
        buttons : [
          'csv','excel','pdf','print'
        ]
      });
    }
      
  });

   
</script>
@endsection