routes/admin.php
    Route::get('admin/movies/link/{id}', 'MovieController@multiplelinks')->name('movies.link');
    Route::post('admin/movies/createlink/{id}', 'MovieController@storelink')->name('movies.storelink');
    Route::patch('admin/movies/editlink/{id}', 'MovieController@editlink')->name('movies.editlink');
    Route::delete('admin/movies/deletelink/{id}', 'MovieController@deletelink')->name('movies.deletelink');

    Route::get('admin/movies/tmdb/translations', 'MovieController@tmdb_translations')->name('tmdb_movie_translate');
    Route::post('admin/movies/bulk_delete', 'MovieController@bulk_delete');

    // live tv routes
    Route::resource('admin/livetv', 'LiveTvController');
    Route::get('admin/livetv/upload_video/converting', 'LiveTvController@upload_video');
    Route::get('admin/livetv/vimeoapi', 'LiveTvController@vimeoApicall');

    Route::get('admin/livetv/tmdb/translations', 'LiveTvController@tmdb_translations')->name('tmdb_movie_translate');
    Route::post('admin/livetv/bulk_delete', 'LiveTvController@bulk_delete');

    // director controller

    Route::resource('admin/directors', 'DirectorController');
    Route::post('admin/directors/bulk_delete', 'DirectorController@bulk_delete');
    Route::resource('admin/actors', 'ActorController');
    Route::post('admin/actors/bulk_delete', 'ActorController@bulk_delete');

    // Genres Routes
    Route::resource('admin/genres', 'GenreController');
    Route::post('admin/genres/bulk_delete', 'GenreController@bulk_delete');
    Route::get('admin/update-to-english', 'GenreController@updateAll');

    Route::get('admin/front/slider/limit', 'SlideUpdateController@get')->name('front.slider.limit');

    Route::post('admin/front/slider/limit/{id}', 'SlideUpdateController@update')->name('front.slider.update');

    Route::resource('admin/packages', 'PackageController');
    Route::delete('/admin/packages/softdelete/{id}', 'PackageController@softDelete');
    Route::post('admin/packages/bulk_delete', 'PackageController@bulk_delete');
    Route::post('admin/packages/reposition', 'PackageController@reposition')->name('package_reposition');
    Route::resource('admin/faqs', 'FaqController');
    Route::post('admin/faqs/bulk_delete', 'FaqController@bulk_delete');
    Route::post('admin/faqs/reposition', 'FaqController@reposition')->name('faqs_reposition');
    Route::resource('admin/languages', 'LanguageController');
    Route::post('admin/languages/bulk_delete', 'LanguageController@bulk_delete');
    Route::resource('admin/settings', 'ConfigController');
    Route::get('admin/api-settings', 'ConfigController@setApiView');
    Route::post('admin/api-settings', 'ConfigController@changeEnvKeys');

    /*Mail Setting Routes*/
    Route::get('/admin/mail-setting', 'ConfigController@getset')->name('mail.getset');
    Route::post('admin/mail-settings', 'ConfigController@changeMailEnvKeys');
    /* end */

    /*Custom style css ad js routes*/
    Route::get('/admin/custom-style-settings', 'CustomStyleController@addStyle')->name('customstyle');
    Route::post('/admin/custom-style-settings/addcss', 'CustomStyleController@storeCSS')->name('css.store');
    Route::post('/admin/custom-style-settings/addjs', 'CustomStyleController@storeJS')->name('js.store');
    /*end*/

    /*custom price text routes*/
    Route::get('/admin/pricing-text-set/{planid}', 'CustomStyleController@pricingText')->name('pricing.text');
    Route::post('/admin/pricing-text-settings/update', 'CustomStyleController@pricingTextUpdate')->name('pr.update');
    Route::get('/admin/pricing-text-settings/get/{id}', 'CustomStyleController@getpricingText')->name('pricing.get');
    /*end*/

    Route::get('/admin/customize/social', 'SocialIconController@get')->name('social.ico');
    Route::post('/admin/customize/social', 'SocialIconController@post')->name('socialic');

    // notification route
    Route::resource('/admin/notification', 'NotificationController');
    Route::get('/admin/notification/send', 'NotificationController@sendNotification');
    Route::post('admin/notification/bulk_delete', 'NotificationController@bulk_delete');

    Route::resource('admin/seo', 'SeoController');
    Route::resource('admin/plan', 'PlanController');

    Route::post('admin/plan/bulk_delete', 'PlanController@bulk_delete');
    Route::post('admin/plan/change_subscription', 'PlanController@change_subscription');

    
    //Google Ads

    Route::get('admin/googleads/', 'GoogleAdsController@index')->name('google.ads');
    Route::get('admin/googleads/create', 'GoogleAdsController@create')->name('google.ads.create');
    Route::post('admin/googleads/create', 'GoogleAdsController@store')->name('google.ads.store');
    Route::get('admin/googleads/edit/{id}', 'GoogleAdsController@edit')->name('google.ads.edit');
    Route::put('admin/googleads/update/{id}', 'GoogleAdsController@update')->name('google.ads.update');
    Route::delete('admin/googleads/delete/{id}', 'GoogleAdsController@destroy')->name('google.ads.delete');
    Route::post('admin/googleads/bulk_delete', 'GoogleAdsController@bulk_delete');

    //ajax director
    Route::get('admin/directors/using/ajax', 'DirectorController@ajaxstore')->name('ajax.director');
    Route::get('admin/listofd', 'DirectorController@listofd')->name('listofd');

    //ajax actor

    Route::get('admin/actors/using/ajax', 'ActorController@ajaxstore')->name('ajax.actor');
    Route::get('admin/listofactor', 'ActorController@listofactor')->name('listofactor');

    // coupon controllers
    Route::resource('admin/coupons', 'CouponController');
    Route::post('admin/coupons/bulk_delete', 'CouponController@bulk_delete');
    Route::resource('admin/home_slider', 'HomeSliderController');
    Route::post('admin/home_slider/bulk_delete', 'HomeSliderController@bulk_delete');
    Route::post('admin/home_slider/reposition', 'HomeSliderController@slide_reposition')->name('slide_reposition');

    Route::get('admin/report', 'ReportController@get_report');

    /**************** revenue report ************************/
    Route::get('admin/report_revenue', 'ReportController@get_revenue_report')->name('revenue.report');
    Route::get('admin/report/data', 'ReportController@ajaxonLoad')->name('ajaxdatefilter');

    /*page setting routes*/
    Route::get('/admin/page-settings/', 'CustomStyleController@getPage')->name('pageset');

    Route::put('/admin/page-settings/{id}', 'CustomStyleController@updatePage')->name('pageset.update');

    /*Social Login setting routes*/
    Route::get('/admin/social-login/', 'SocialLoginController@index')->name('sociallogin');
    Route::put('/admin/social-login/{id}', 'SocialLoginController@updatePage')->name('sociallogin.update');
    Route::get('admin/social-login/', 'SocialLoginController@facebook')->name('set.facebook');
    Route::post('admin/facebook', 'SocialLoginController@updateFacebookKey')->name('key.facebook');
    Route::post('admin/google', 'SocialLoginController@updateGoogleKey')->name('key.google');
    Route::post('admin/gitlab', 'SocialLoginController@updategitlabKey')->name('key.gitlab');
    Route::post('admin/amazon', 'SocialLoginController@updateamazonKey')->name('key.amazon');

    /*end*/
    // adsense routes
    Route::get('/admin/adsensesetting/', 'AdsenseController@index')->name('adsense');
    Route::put('/admin/adsensesetting/{id}', 'AdsenseController@update')->name('adsense.update');

    /////////////////////////
    // Customizable Routes //
    /////////////////////////
    Route::resource('admin/customize/landing-page', 'LandingPageController');
    Route::post('admin/customize/landing-page/bulk_delete', 'LandingPageController@bulk_delete');
    Route::post('admin/customize/landing-page/reposition', 'LandingPageController@reposition')->name('landing_page_reposition');
    Route::get('admin/customize/auth-page-customize', 'AuthCustomizeController@index');
    Route::post('admin/customize/auth-page-customize', 'AuthCustomizeController@store');

    /////////////////////////
    // Customizable pages Routes //
    /////////////////////////
    Route::resource('admin/custom_page', 'CustomPageController');

    Route::resource('admin/home-block', 'HomeBlockController');

    Route::post('admin/home-block/bulk_delete', 'HomeBlockController@bulk_delete');


    Route::post('admin/custom_page/destroy/{id}', 'CustomPageController@destroy')->name('custom-page.destroy');
    Route::post('admin/custom_page/bulk_delete', 'CustomPageController@bulk_delete');

    //PWA Settings

    Route::get('/pwa-settings', 'PWAController@index')->name('pwa.setting.index');

    Route::post('/pwa/update/setting', 'PWAController@updatesetting')->name('pwa.setting.update');

    Route::post('/pwa/update/icons/setting', 'PWAController@updateicons')->name('pwa.icons.update');

    //manual payment

    Route::resource('admin/manual-payment', 'ManualPaymentController');

    //chat settings
    Route::get('admin/chat_settings', 'ChatSettingController@index')->name('chat.index');

    Route::post('admin/chat_settings', 'ChatSettingController@update');

    // Site Policies Get Method
    Route::get('admin/term&con', function () {
        $config = \App\Config::whereId(1)->first();
        return view('admin.term&con', compact('config'));
    })->name('term_con');
    Route::get('admin/pri_pol', function () {
        $config = \App\Config::whereId(1)->first();
        return view('admin.pri_pol', compact('config'));
    })->name('pri_pol');
    Route::get('admin/refund_pol', function () {
        $config = \App\Config::whereId(1)->first();
        return view('admin.refund_pol', compact('config'));
    })->name('refund_pol');
    Route::get('admin/copyright', function () {
        $config = \App\Config::whereId(1)->first();
        return view('admin.copyright', compact('config'));

routes/web.php
    Route::get('show/save/{upload_video}', 'PrimeDetailController@seasondownload')->name('season.download');
    Route::get('/user/movie/time/{endtime}/{movie_id}/{user_id}/{totaltime}', 'TimeHistoryController@movie_time');
    Route::get('/user/tv/time/{endtime}/{tv_id}/{totaltime}', 'TimeHistoryController@tv_time');
    Route::get('/user/watchhistory/{movie_id}/{type}', 'TimeHistoryController@watchhistory');

    Route::get('/user/episode/time/{endtime}/{episode_id}/{user_id}/{tv_id}/{totaltime}', 'TimeHistoryController@episode_time');

    // like and comment routes

    Route::get('comment/index', 'CommentController@index');
    Route::get('movie/comment/index', 'MovieCommentController@index');

    Route::post('movie/comment/store/{id}', 'MovieCommentController@store')->name('movie.comment.store');

    Route::post('movie/comment/reply/{cid}', 'MovieCommentController@reply')->name('movie.comment.reply');

    Route::delete('movie/comment/delete/{id}', 'MovieCommentController@deletecomment')->name('movie.comment.delete');

    Route::delete('movie/comment/reply/delete/{cid}', 'MovieCommentController@deletesubcomment')->name('movie.comment.subdelete');

    Route::get('comment/index', 'CommentController@index');

    Route::get('tvseries/comment/index', 'TVCommentController@index');

    Route::post('tvseries/comment/store/{id}', 'TVCommentController@store')->name('tv.comment.store');

    Route::post('tvseries/comment/reply/{cid}', 'TVCommentController@reply')->name('tv.comment.reply');

    Route::delete('tvseries/comment/delete/{id}', 'TVCommentController@deletecomment')->name('tv.comment.delete');

    Route::delete('tvseries/comment/reply/delete/{cid}', 'TVCommentController@deletesubcomment')->name('tv.comment.subdelete');

    Route::get('unlike/unlike', 'LikeController@unlike')->name('unlike');

    Route::get('like/add', 'LikeController@add')->name('addtolike');

    Route::post('comment/store/{id}', 'CommentController@store')->name('comment.store');

    Route::post('comment/reply/{cid}/{bid}', 'CommentController@reply')->name('comment.reply');

    Route::delete('blog/comment/delete/{id}', 'CommentController@deletecomment')->name('blog.comment.delete');

    Route::delete('blog/comment/reply/delete/{bid}', 'CommentController@deletesubcomment')->name('blog.comment.subdelete');

    Route::get('/movietrailer/{user}/{code}/{id}', 'WatchApiController@watch_trailer');
    Route::get('/watchmovie/{user}/{code}/{id}', 'WatchApiController@watch_movie');
    Route::get('/watchepisode/{user}/{code}/{id}', 'WatchApiController@watch_episode');
    Route::get('/watch/movie/iframe/{user}/{code}/{id}', 'WatchApiController@watch_iframe')->name('watchiframe');
    //api payment thankyou
    Route::get('/payment-successfully', 'WatchApiController@paymentSuccess');

    Route::get('verifyEmailFirst', 'Auth\RegisterController@verifyEmailFirst')->name('verifyEmailFirst');

    Route::get('verify/{email}/{verifyToken}', 'Auth\RegisterController@sendEmailDone')->name('sendEmailDone');

    // Test Controller Route to play video

    Route::get('/player', 'TestController@getVideo');

    // Paytem Routes
    Route::resource('/paytem', 'PaytemController');
    Route::get('/paytm-payment-redirect', 'PaytemController@handlePaytmRequest');
    Route::post('/paytm-callback', 'PaytemController@paytmCallback');

    //freepackagesubscription
    Route::post('free/subscription/{planid}', 'ManualPaymentController@freePackageSubscription')->name('free.package.subscription');

    // Routes With Only Language Switch Middleware
    Route::group(['middleware' => ['switch_languages']], function () {
        //Catlog view menus for user without logging in
        Route::get('/guest/{menus}', 'HomeController@guestindex')->name('guests');
        Route::get('/guest/watch/{id}', 'WatchController@watch')->name('guestwatchtrailer');
        Route::get('movie/guest/detail/{slug}', 'PrimeDetailController@showMovie');
        Route::get('/guest', 'HomeController@mainPage');
        Route::get('/guest/viewall/{menuid}/{menuname}', 'HomeController@showall')->name('guestshowall');
        Route::get('/guest/viewall/movies', 'HomeController@showallsinglemovies')->name('guestshowall2');
        Route::get('movies/guest/genre/{id}', 'HomeController@movie_genre');
        

        Route::get('show/all/guest/genres/{id}', 'HomeController@gusetshowallgenre')->name('show.in.guest.genre');
        Route::get('show/all/guest/langs/{id}', 'HomeController@guestshowallalang')->name('show.in.guest.alang');

        Route::get('home/search', 'HomeController@search')->name('search');
        Route::get('quick/search', 'HomeController@quicksearch')->name('quick.search');

        Route::get('video/detail/director_search/{director}', 'HomeController@director_search');
        Route::get('video/detail/actor_search/{actor}', 'HomeController@actor_search');
        Route::get('video/detail/genre_search/{genre}', 'HomeController@genre_search');

        Route::get('/page/{slug}', 'CustomPageController@show')->name('custom.page.show');

        if (Auth::user()) {
            // menu routes
            Route::get('/{menu}', 'HomeController@index')->name('home');
        } else {
            // main page route
            Route::get('/', 'HomeController@mainPage');

        }

        // Faq routes

        Route::get('faq', function () {
            $faqs = Faq::all();
            return view('faq', compact('faqs'));
        });

        // general pages routes
        Route::view('terms_condition', 'term_condition');
        Route::view('privacy_policy', 'privacy_pol');
        Route::view('refund_policy', 'refund_pol');
        Route::view('seo', 'seo');

        // Auth Routes
        Auth::routes();

    });

    //Affiliate route

    Route::get('/user/affiliate/settings', 'AffilateController@userdashboard')->name('user.affiliate.settings');

    //2FA
    Route::post('/valid-2fa', 'TwoFactorController@login')->middleware('auth');

    // Language switch middleware
    Route::get('language-switch/{local}', 'LanguageSwitchController@languageSwitch')->name('languageSwitch');

    // Routes With Web, Auth Middlewares
    Route::get('contactus', 'ContactController@contact')->name('contactus');
    Route::post('send/contactus', 'ContactController@send')->name('send.contactus');   
     
    Route::group(['middleware' => ['web', 'auth', 'switch_languages']], function () {
        // User Account routes without subscription
        Route::get('account', 'UserAccountController@index');

        Route::post('/payviarazorpaysuccess/{planid}', 'PayViaRazorpayController@success')->name('paysuccess');

        
        Route::get('account/profile', 'UserAccountController@edit_profile');
        Route::post('account/profile', 'UserAccountController@update_profile')->name('user.profile');
        Route::post('account/profile/age', 'UsersController@update_age')->name('user.age');
        Route::post('account/profile/address', 'UsersController@update_address')->name('user.address');
        Route::post('account/profile/uploadimage', 'UsersController@update_image')->name('user.uploadImage');
        Route::post('account/other/settings', 'UserAccountController@update_otherprofilesetting')->name('user.other.profile');
        Route::get('account/purchaseplan', 'UserAccountController@purchase_plan');
        Route::get('account/purchase/{id}', 'UserAccountController@get_payment')->name('get_payment');
        Route::post('account/purchase', 'UserAccountController@subscribe');
        Route::get('account/billing_history', 'UserAccountController@history');
        Route::post('emailsubscribe', 'emailSubscribe@subscribe');
        Route::post('paypal_subscription', 'PaypalController@postPaymentWithpaypal')->name('paypal_subscription');
        Route::get('paypal_subscription', 'PaypalController@getPaymentStatus')->name('getPaymentStatus');
        Route::get('paypal_subscription_failed', 'PaypalController@getPaymentFailed')->name('getPaymentFailed');
        // rating routes
        Route::POST('video/rating', 'UserRatingController@store');
        Route::POST('video/rating/tv', 'UserRatingController@tvstore');
        // susbscription routes
        Route::get('payment/braintree', 'BrainTreeController@get_bt');
        Route::post('payment/braintree', 'BrainTreeController@payment');
        Route::get('payment/coinpayment', 'CoinpaymentsController@get_bt');
        Route::post('payment/coinpayment', 'CoinpaymentsController@purchaseItems');
        Route::post('payment/paystack', 'PaystackController@paystackgateway');
        Route::get('paystack/callback', 'PaystackController@paystackcallback');
        // Paypal Routes
        Route::get('paypal/cancel-subscription', 'UserAccountController@PaypalCancel')->name('cancelSubPaypal');
        Route::get('paypal/resume-subscription', 'UserAccountController@PaypalResume')->name('resumeSubPaypal');

        # Status Route
        Route::get('payment/status', 'PayuController@status');
        Route::post('payment/payu', 'PayuController@payment');

        //Instamojo Routes
        Route::post('pay/instamojo', 'PayViaInstamojoController@pay')->name('payinstamojo');
        Route::get('instamojo/pay-success', 'PayViaInstamojoController@success');

        //Mollie Payment Routes

        Route::post('payviamollie/subscription', 'PayViaMollieController@payment')->name('payviamoli_subscription');
        Route::get('paymentmolliedone/status', 'PayViaMollieController@success')->name('moli.pay.success_subscription');

        // Cash free payment routes
        Route::post('/payviacashfree', 'PayViaCashFreeController@payment')->name('payviacashfree');
        Route::post('/cashfree/success', 'PayViaCashFreeController@success')->name('payviacashfreesuccess');

        // Omise Payment routes
        Route::post('/payviaomise', 'OmiseController@pay')->name('pay.via.omise');

        //Flutterrave route

resources/views/admin/plan/change_sub.blade.php
@extends('layouts.master')
@section('title',__('Alterar assinatura'))
@section('breadcum')
	<div class="breadcrumbbar">
                <h4 class="page-title">{{ __('Alterar assinatura') }}</h4>
                <div class="breadcrumb-list">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item"><a href="{{url('/admin')}}">{{ __('Dashboard') }}</a></li>
                      <li class="breadcrumb-item active" aria-current="page">{{ __('Alterar assinatura') }}</li>
                    </ol>
                </div>
    </div>
@endsection
@section('maincontent')
<div class="contentbar">
  <div class="row">
    @if ($errors->any())  
      <div class="alert alert-danger" role="alert">
        @foreach($errors->all() as $error)     
          <p>{{ $error}}<button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true" style="color:red;">&times;</span></button></p>
        @endforeach  
       </div>
    @endif
    <div class="col-lg-6">
      <div class="card m-b-30">
        <div class="card-header">
          <a href="{{url('admin/plan')}}" class="float-right btn btn-primary-rgba mr-2"><i
              class="feather icon-arrow-left mr-2"></i>{{ __('Voltar') }}</a>
          <h5 class="box-title">{{__('Change Subscription')}}</h5>
        </div>
        <div class="card-body ml-2">
          {!! Form::open(['method' => 'POST', 'action' => 'UsersController@change_subscription', 'files' => true]) !!}
          <h5 class="box-title">{{__('User Name')}}: {{$user->name}}</h5>
            @php
              if (isset($plans)) {
                $planname='not exist';
                  if (isset($last_payment->plan->name) && !is_null($last_payment)){
                    $planname=$last_payment->plan->name;
                  }else{
                    if (isset($user_stripe_plan) && !is_null($user_stripe_plan)) {
                    $planname=$user_stripe_plan->name;
                    }
                  }
              
              }else{
                  $planname='not exist';
              }
            @endphp
            <h5 class="box-title">{{__('Plano atual')}}: {{$planname}}</h5>
              <div class="col-md-12">
                <input type="hidden" name="user_stripe_plan_id" value="{{$user_stripe_plan != null ? $user_stripe_plan->id : null}}">
                <input type="hidden" name="last_payment_id" value="{{$last_payment != null ? $last_payment->id : null}}">
                <input type="hidden" name="user_id" value="{{$user->id}}">
                <div class="form-group{{ $errors->has('plan') ? ' has-error' : '' }}">
                  {!! Form::label('plan',__('Selecione um novo plano')) !!} 
                  <p class="inline info"> - {{__('Defina um novo plano para este usuário')}}</p>
                  {!! Form::select('plan_id', $plan_list, null, ['class' => 'form-control select2', 'required' => 'required', 'autofocus']) !!}
                  <small class="text-danger">{{ $errors->first('plan') }}</small>
                </div>
              </div>
              
              <div class="form-group">
                <button type="submit" class="btn btn-primary-rgba"><i class="fa fa-check-circle"></i>{{ __('Change Subscription') }}</button>
              </div>
          {!! Form::close() !!}
        </div>
      </div>
    </div>
  </div>
</div>
@endsection 
@section('script')

@endsection

resources/views/admin/plan/create.blade.php
@extends('layouts.admin')
@section('content')
  <div class="admin-form-main-block mrgn-t-40">
    <h4 class="admin-form-text"><a href="{{url('admin/plan')}}" data-toggle="tooltip" data-original-title="Go back" class="btn-floating"><i class="material-icons">reply</i></a> Create User</h4>
    <div class="row">
      <div class="col-md-6">
        <div class="admin-form-block z-depth-1">          
          {!! Form::open(['method' => 'POST', 'action' => 'PlanController@store', 'files' => true]) !!}
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
              {!! Form::label('name',__('Enter Name')) !!} 
              <p class="inline info"> - Please enter your name</p>
              {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required', 'autofocus']) !!}
              <small class="text-danger">{{ $errors->first('name') }}</small>
            </div>
            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
              {!! Form::label('email', 'Email address') !!}
              <p class="inline info"> - Please enter your email</p>
              {!! Form::email('email', null, ['class' => 'form-control', 'required' => 'required']) !!}
              <small class="text-danger">{{ $errors->first('email') }}</small>
            </div>
            <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
              {!! Form::label('password', 'Password') !!}
              <p class="inline info"> - Please enter your password</p>
              {!! Form::password('password', ['class' => 'form-control', 'required' => 'required']) !!}
              <small class="text-danger">{{ $errors->first('password') }}</small>
            </div>
            <div class="form-group{{ $errors->has('confirm_password') ? ' has-error' : '' }}">
              {!! Form::label('confirm_password', 'Confirm Password') !!}
              <p class="inline info"> - Please enter your password again</p>
              {!! Form::password('confirm_password', ['class' => 'form-control', 'required' => 'required']) !!}
              <small class="text-danger">{{ $errors->first('confirm_password') }}</small>
            </div>
            <div class="form-group{{ $errors->has('is_admin') ? ' has-error' : '' }} switch-main-block">
              <div class="row">
                <div class="col-xs-4">
                  {!! Form::label('is_admin', 'Administrator') !!}
                </div>
                <div class="col-xs-5 pad-0">
                  <label class="switch">								
                    {!! Form::checkbox('is_admin', 1, 0, ['class' => 'checkbox-switch']) !!}
                    <span class="slider round"></span>
                  </label>
                </div>
              </div>
              <div class="col-xs-12">
                <small class="text-danger">{{ $errors->first('is_admin') }}</small>
              </div>
            </div>
            <div class="btn-group pull-right">
              <button type="reset" class="btn btn-info">Reset</button>
              <button type="submit" class="btn btn-success">Create</button>
            </div>
            <div class="clear-both"></div>
          {!! Form::close() !!}
        </div>  
      </div>
    </div>
  </div>
@endsection
@section('custom-script')
<script>
  $(function(){
    $('form').on('submit', function(event){
      $('.loading-block').addClass('active');
    });
  });
</script>
@endsection

resources/views/admin/plan/index.blade.php
@extends('layouts.master')
@section('title',__('Assinantes'))
@section('breadcum')
	<div class="breadcrumbbar">
                <h4 class="page-title">{{ __('Assinantes') }}</h4>
                <div class="breadcrumb-list">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item"><a href="{{url('/admin')}}">{{ __('Dashboard') }}</a></li>
                      <li class="breadcrumb-item active" aria-current="page">{{ __('Change Subscription') }}</li>
                    </ol>
                </div>    
    </div>
@endsection
@section('maincontent')
<div class="contentbar"> 
  <div class="row">
    <div class="col-md-12">
      <div class="card m-b-50">
        <div class="card-body">
          <div class="table-responsive">
            <table id="plan_table" class="table table-borderd">
              <thead>
                <th>{{__('ID')}}</th>
                <th>{{__('Nome')}}</th>
                <th>{{__('Email')}}</th>
                <th>{{__('Plano')}}</th>
                <th>{{__('Próxima expiração')}}</th>
                <th>{{__('Ações')}}</th>
              </thead>
              <tbody>
              
              </tbody>
            </table>                  
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection  
@section('script')
   
<script>
  $(function () {
    jQuery.noConflict();
    var table;
    if($.fn.dataTable.isDataTable('#plan_table')){
      table = $('#plan_table').DataTable();
    }else{
      table = $('#plan_table').DataTable({
        processing: true,
        serverSide: true,
         responsive: true,
        autoWidth: false,
        scrollCollapse: true,
     
        ajax: "{{ route('plan.index') }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex'},
            {data: 'username', name: 'username'},
            {data : 'useremail', name: 'useremail'},
            {data : 'planname', name: 'planname'},
            {data : 'subscription_to', name : 'subscription_to'},
            {data : 'action', name: 'action'}
    
        ],
        dom : 'lBfrtip',
        buttons : [
          'csv','excel','pdf','print'
        ],
        order : [[0,'DESC']]
      });
    }
    
    
  });
</script>

@endsection